const drills={coding:{number:'01',note:'Explain your approach before you optimize. After a realistic interview, personalized feedback gives you something specific to practice next.',question:'Given an array and a target, find the indices of two numbers that sum to that target. Talk through your initial approach and one improvement.',review:'Self-review: did you explain the hash-map approach, avoid reusing an index, and state O(n) time and O(n) extra space?'},system:{number:'02',note:'Set the requirements before drawing the architecture. Your AI coach helps you practice making design choices and tradeoffs clear.',question:'Design a URL shortener. Use the warm-up to clarify requirements and outline the main components.',review:'Self-review: did you clarify volume, expiry, and custom aliases? Can you explain the storage choice and one scaling bottleneck?'},behavioral:{number:'03',note:'Make your contribution clear. Realistic behavioral practice and personalized feedback help sharpen the story without losing your voice.',question:'Tell me about a disagreement on a technical project. How did you handle it, and what changed?',review:'Self-review: did you give brief context, explain your action, name the outcome, and reflect on what you learned?'}};
let selected='coding',interval=null,remaining=120,running=false,deadline=0;
const start=document.querySelector('#start');const status=document.querySelector('#status');const pause=document.querySelector('#pause');
function showTime(){document.querySelector('#clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');}
function stopClock(){clearInterval(interval);interval=null;running=false;}
function runClock(){running=true;deadline=Date.now()+remaining*1000;status.textContent='ACTIVE';pause.textContent='Pause clock';interval=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));showTime();if(remaining===0){stopClock();status.textContent='TIME UP';pause.disabled=true;document.querySelector('#question').textContent=drills[selected].question+' Warm-up time is up. Continue at your own pace, then finish and review.';}},250);}
function reset(){stopClock();remaining=120;showTime();status.textContent='READY';pause.disabled=false;pause.textContent='Pause clock';start.hidden=false;document.querySelector('#active-drill').hidden=true;document.querySelector('#review').hidden=true;}
document.querySelectorAll('[data-drill]').forEach(button=>button.addEventListener('click',()=>{reset();selected=button.dataset.drill;document.querySelectorAll('[data-drill]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelector('#drill-number').textContent=drills[selected].number;document.querySelector('#coach-note').textContent=drills[selected].note;}));
start.addEventListener('click',()=>{start.hidden=true;document.querySelector('#active-drill').hidden=false;document.querySelector('#review').hidden=true;document.querySelector('#question').textContent=drills[selected].question;runClock();pause.focus();});
pause.addEventListener('click',()=>{if(running){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));stopClock();showTime();status.textContent='PAUSED';pause.textContent='Resume clock';}else if(remaining>0){runClock();}});
document.querySelector('#finish').addEventListener('click',()=>{stopClock();status.textContent='REVIEW';document.querySelector('#active-drill').hidden=true;document.querySelector('#review').hidden=false;document.querySelector('#review-text').textContent=drills[selected].review+' This is a predefined checklist, not an AI evaluation.';document.querySelector('#reset').focus();});
document.querySelector('#reset').addEventListener('click',()=>{reset();start.focus();});
