const starts=[...document.querySelectorAll('[data-start]')];
const tools=document.querySelector('#practice-tools');
const status=document.querySelector('#status');
const timer=document.querySelector('#timer');
let interval=null,startedAt=0,state='ready';
function tick(){const seconds=Math.floor((Date.now()-startedAt)/1000);timer.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}
function begin(){if(state!=='ready')return;state='active';starts.forEach(button=>button.hidden=true);tools.hidden=false;document.querySelector('#end').hidden=false;document.querySelector('#review').hidden=true;document.querySelector('#action-note').hidden=true;document.querySelector('#session-link').hidden=false;status.textContent='● Sample interview in progress';document.querySelector('#question-label').textContent='YOUR FIRST QUESTION';document.querySelector('#greeting').textContent='Let’s begin. Talk me through your approach to the problem in the session brief. What assumptions would you clarify first?';startedAt=Date.now();tick();interval=setInterval(tick,1000);document.querySelector('#notes').focus();}
starts.forEach(button=>button.addEventListener('click',begin));
document.querySelector('#end').addEventListener('click',()=>{if(state!=='active')return;state='review';clearInterval(interval);interval=null;document.querySelector('#end').hidden=true;status.textContent='✓ Sample session complete';document.querySelector('#greeting').textContent='Nice work making time to practice. Use the self-review checklist to choose one thing to improve next time.';document.querySelector('#review').hidden=false;document.querySelector('#again').focus();});
document.querySelector('#again').addEventListener('click',()=>{clearInterval(interval);interval=null;state='ready';starts.forEach(button=>button.hidden=false);tools.hidden=true;document.querySelector('#review').hidden=true;document.querySelector('#action-note').hidden=false;document.querySelector('#session-link').hidden=true;status.textContent='● Ready when you are';timer.textContent='00:00';document.querySelector('#notes').value='';document.querySelector('#question-label').textContent='QUESTION PREVIEW';document.querySelector('#greeting').textContent='We’ll practice a realistic SWE interview, then review your reasoning, communication, and next steps.';starts[0].focus();});
