const choices=[
 {name:'Two Sum, one good conversation.',type:'CODING / ALGORITHMS',description:'Looking for someone who can explain their approach, not just find the answer.',tags:['Hash maps','Thinking aloud','Complexity'],question:'How would you find two numbers that add up to a target?',hint:'Compare a nested-loop approach with a hash map. Explain the memory tradeoff and avoid using the same index twice.',palette:'peach',motif:['{','♡','}']},
 {name:'A system with a little ambition.',type:'SYSTEM DESIGN',description:'Big ideas welcome. Clear requirements and thoughtful tradeoffs preferred.',tags:['Architecture','Scaling','Tradeoffs'],question:'How would you design a URL shortener for a growing service?',hint:'Clarify traffic, custom aliases, and link expiration before discussing storage and scaling.',palette:'blue',motif:['○','↔','○']},
 {name:'The story only you can tell.',type:'BEHAVIORAL',description:'Interested in ownership, learning, and what you did when things got difficult.',tags:['Teamwork','Reflection','Clarity'],question:'Tell me about a time you got stuck on a technical problem. What did you do?',hint:'Use brief context, your action, the outcome, and what you learned. Make your own contribution visible.',palette:'lilac',motif:['“','✦','”']},
 {name:'A cache with good memory.',type:'CODING / DATA STRUCTURES',description:'Values quick lookups, thoughtful ordering, and knowing when to let go.',tags:['LRU cache','Data structures','Tradeoffs'],question:'How would you implement a least-recently-used cache with efficient get and put operations?',hint:'Think about a hash map for lookup and a doubly linked list to maintain access order.',palette:'green',motif:['[','∞',']']},
 {name:'Reliable, even under pressure.',type:'BACKEND / RELIABILITY',description:'Likes consistent behavior and avoids doing the same important thing twice.',tags:['Idempotency','Retries','Correctness'],question:'A client retries a payment after a timeout. How would you prevent charging twice?',hint:'Discuss idempotency keys and how the server records completed requests.',palette:'blue',motif:['↺','✓','↺']}
];
let index=0,matched=null,pointer=null;const profile=document.querySelector('#profile');const start=document.querySelector('#start');
function render(){const empty=index>=choices.length;profile.hidden=empty;document.querySelector('#empty').hidden=!empty;document.querySelector('#skip').disabled=empty;document.querySelector('#match').disabled=empty;document.querySelector('#counter').textContent=empty?'5 / 5':(index+1)+' / 5';if(empty)return;const c=choices[index];document.querySelector('#profile-type').textContent=c.type;document.querySelector('#profile-name').textContent=c.name;document.querySelector('#profile-description').textContent=c.description;document.querySelector('#profile-prompt').textContent='“'+c.question+'”';document.querySelector('#profile-art').dataset.palette=c.palette;const tags=document.querySelector('#tags');tags.replaceChildren();c.tags.forEach(text=>{const span=document.createElement('span');span.textContent=text;tags.append(span);});const motif=document.querySelector('#motif');motif.replaceChildren();c.motif.forEach(text=>{const span=document.createElement('span');span.textContent=text;motif.append(span);});}
function choose(match){if(index>=choices.length)return;const choice=choices[index];if(match){matched=choice;document.querySelector('#match-title').textContent='It’s a practice match!';document.querySelector('#match-copy').textContent=choice.name+' Start a realistic mock interview and let your AI coach help you find the next improvement.';document.querySelector('#match-type').textContent=choice.type;document.querySelector('#swipe-status').textContent='Matched: '+choice.name;}else document.querySelector('#swipe-status').textContent='Passed. Try the next practice choice.';index++;render();}
document.querySelector('#skip').addEventListener('click',()=>choose(false));document.querySelector('#match').addEventListener('click',()=>choose(true));
profile.addEventListener('pointerdown',event=>{if(event.isPrimary===false)return;pointer={id:event.pointerId,x:event.clientX,y:event.clientY};profile.setPointerCapture(event.pointerId);});
profile.addEventListener('pointerup',event=>{if(!pointer||pointer.id!==event.pointerId)return;const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;pointer=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)choose(dx>0);});
profile.addEventListener('pointercancel',()=>{pointer=null;});
document.querySelector('#replay').addEventListener('click',()=>{index=0;render();document.querySelector('#swipe-status').textContent='The deck is ready again. Your selected match is still available.';document.querySelector('#match').focus();});
const dialog=document.querySelector('#interview');start.addEventListener('click',()=>{const c=matched||choices[index]||choices[0];document.querySelector('#dialog-title').textContent=c.name;document.querySelector('#dialog-question').textContent=c.question+' Talk through your approach aloud.';document.querySelector('#dialog-hint').textContent=c.hint;document.querySelector('#interview details').open=false;dialog.showModal();});
document.querySelector('#close').addEventListener('click',()=>dialog.close());
