const acts=[
 {indicator:'ACT I / THE REHEARSAL',label:'ACT I · A ROOM TO TRY',title:'The first attempt<br>belongs here.',copy:'Before your real SWE interview, rehearse the conversation. Work through realistic coding, system design, and behavioral questions with an AI interviewer that asks you to explain your thinking.',speaker:'YOUR AI COACH',line:'“Take your time. Start by telling me how you’d approach the problem.”',note:'You don’t need a perfect answer to begin.'},
 {indicator:'ACT II / THE REFLECTION',label:'ACT II · THE USEFUL NOTES',title:'Every attempt<br>leaves a clue.',copy:'After a realistic mock interview, get personalized feedback on your reasoning, solution, and communication. Find the strengths to keep and the gaps that deserve another rehearsal.',speaker:'SAMPLE COACHING NOTE',line:'“You explained your approach clearly. Next time, make the space-complexity tradeoff explicit.”',note:'Illustrative feedback, not an evaluation of your answer.'},
 {indicator:'ACT III / THE RETURN',label:'ACT III · A STRONGER ENTRANCE',title:'Return with<br>one thing clearer.',copy:'Choose one improvement and practice again. Build the habit of explaining, reflecting, and refining — so your next real interview feels a little more familiar.',speaker:'YOUR NEXT REHEARSAL',line:'“This time, I’ll walk through an edge case before I wrap up.”',note:'No perfect performance required. Just another useful attempt.'}
];
let current=0;
function select(index){current=index;const act=acts[index];document.querySelectorAll('[data-act]').forEach(b=>{const active=Number(b.dataset.act)===index+1;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});document.querySelector('#act-indicator').textContent=act.indicator;document.querySelector('#scene-label').textContent=act.label;document.querySelector('#scene-title').innerHTML=act.title;document.querySelector('#scene-copy').textContent=act.copy;document.querySelector('#speaker').textContent=act.speaker;document.querySelector('#line').textContent=act.line;document.querySelector('#scene-note').textContent=act.note;document.querySelector('#next').textContent=index===2?'Back to Act I ↺':'Next act →';}
document.querySelectorAll('[data-act]').forEach(button=>button.addEventListener('click',()=>select(Number(button.dataset.act)-1)));
document.querySelector('#next').addEventListener('click',()=>select((current+1)%3));
const dialog=document.querySelector('#rehearsal');let cue=0;
const cues=[{speaker:'AI INTERVIEWER',line:'Given an array of integers and a target, find two numbers that sum to the target. How would you approach it?'},{speaker:'SAMPLE FOLLOW-UP',line:'How would you improve a nested-loop solution? Explain what you would store in a hash map, and why you check before inserting.'},{speaker:'SELF-REVIEW / PREDEFINED',line:'Did you state assumptions, explain O(n) time and O(n) space, and walk through an edge case? Pick one point to practice on your next attempt.'}];
function renderCue(){document.querySelector('#dialog-speaker').textContent=cues[cue].speaker;document.querySelector('#dialog-line').textContent=cues[cue].line;document.querySelector('#cue').textContent=cue===2?'Rehearse again ↺':'Give me the next cue →';}
document.querySelector('#start').addEventListener('click',()=>{cue=0;renderCue();dialog.showModal();});
document.querySelector('#close').addEventListener('click',()=>dialog.close());
document.querySelector('#cue').addEventListener('click',()=>{cue=(cue+1)%3;renderCue();});
