const missions={coding:{briefing:'Find two indices in an array whose values sum to a target. Clarify whether a solution is guaranteed and how duplicates should be handled.',reasoning:'Explain a simple approach, then describe a hash-map improvement. Why does the lookup help?',followup:'What happens with [3, 3] and target 6? Explain why you check before inserting the current value.',debrief:'Self-review: name O(n) time and O(n) extra space, and explain how you avoid reusing one index.'},system:{briefing:'Design a URL shortener. Clarify traffic, link expiration, and whether custom aliases are required.',reasoning:'Describe the main components and storage model. Tie each design choice to a requirement.',followup:'Which component becomes a bottleneck as reads increase? Explain one scaling tradeoff.',debrief:'Self-review: connect the architecture to requirements, discuss a bottleneck, and name a tradeoff.'},behavioral:{briefing:'Tell me about a time a technical project did not go as planned. Set the context briefly.',reasoning:'Explain your own actions and how you worked with others to move the project forward.',followup:'What would you do differently next time, and why?',debrief:'Self-review: make your contribution visible, describe the outcome, and reflect on one lesson.'}};
const titles=['Clarify the mission.','Explain the approach.','Handle the follow-up.','Turn the debrief into a plan.'];let current=-1,completed=0;const select=document.querySelector('#mission-type');
function draw(){document.querySelector('#progress').value=completed;document.querySelector('#progress-text').textContent=completed+' / 4';document.querySelectorAll('.checkpoints>div').forEach((row,i)=>{row.classList.toggle('active',i===current);row.classList.toggle('complete',i<completed);});for(let i=0;i<4;i++){const node=document.querySelector('#node-'+i);node.classList.toggle('active',i===current);node.classList.toggle('complete',i<completed);}}
function entry(text){const li=document.createElement('li');li.textContent=text;document.querySelector('#log').append(li);}
function checkpoint(){const key=['briefing','reasoning','followup','debrief'][current];document.querySelector('#checkpoint-label').textContent='CHECKPOINT '+String(current+1).padStart(2,'0')+' / LOCAL SAMPLE';document.querySelector('#checkpoint-title').textContent=titles[current];document.querySelector('#checkpoint-copy').textContent=missions[select.value][key];document.querySelector('#advance').textContent=current===3?'Complete the sample mission →':'Acknowledge & advance →';draw();}
function reset(){current=-1;completed=0;draw();document.querySelector('#mission-status').textContent='PRE-LAUNCH';document.querySelector('#checkpoint-label').textContent='MISSION OBJECTIVE';document.querySelector('#checkpoint-title').textContent='Practice the conversation.';document.querySelector('#checkpoint-copy').textContent='Navigate a realistic interview question and follow-up. Your AI coach’s personalized feedback turns the debrief into a focused practice plan.';document.querySelector('#start').hidden=false;document.querySelector('#advance').hidden=true;document.querySelector('#debrief').hidden=true;document.querySelector('#log').replaceChildren();entry('Awaiting your sample mission launch.');select.disabled=false;}
document.querySelector('#start').addEventListener('click',()=>{current=0;completed=0;select.disabled=true;document.querySelector('#start').hidden=true;document.querySelector('#advance').hidden=false;document.querySelector('#mission-status').textContent='MISSION ACTIVE';document.querySelector('#log').replaceChildren();entry('Sample '+select.value+' mission launched.');checkpoint();document.querySelector('#advance').focus();});
document.querySelector('#advance').addEventListener('click',()=>{if(current<0||completed===4)return;completed=current+1;entry('Checkpoint '+String(completed).padStart(2,'0')+' acknowledged.');if(completed<4){current++;checkpoint();}else{current=-1;draw();document.querySelector('#mission-status').textContent='DEBRIEF COMPLETE';document.querySelector('#advance').hidden=true;document.querySelector('#debrief').hidden=false;document.querySelector('#debrief-copy').textContent=missions[select.value].debrief+' This is predefined guidance, not an AI evaluation.';document.querySelector('#reset').focus();}});
select.addEventListener('change',reset);document.querySelector('#reset').addEventListener('click',()=>{reset();document.querySelector('#start').focus();});
