const focuses={
 reasoning:{title:'Make the edge-case reasoning visible.',reason:'The sample answer has an efficient approach but does not show how duplicates are handled. Validate the logic so the interviewer can follow it.',steps:['Walk through [3, 3] with target 6.','Check the complement before inserting the current value.','Explain why that order avoids using one index twice.'],prompt:'Try Two Sum again, this time walking through duplicates and explaining the order of operations.',button:'Practice edge-case reasoning'},
 communication:{title:'Give the explanation a clear starting point.',reason:'The sample response jumps into the solution. Start with assumptions, then explain what you store and why, before describing the loop.',steps:['Clarify whether the answer should return indices or values.','Explain what the hash map contains and why it helps.','Use signposts: approach, example, then complexity.'],prompt:'Try Two Sum again, this time clarifying assumptions and keeping your explanation in sequence.',button:'Practice a clearer explanation'},
 technical:{title:'Make the time-and-space tradeoff explicit.',reason:'The sample answer names linear time but leaves the extra memory unstated. Finish the explanation so the interviewer sees the full cost.',steps:['Explain why each number is visited once.','State O(n) time and O(n) extra space.','Describe what the hash map stores as the input grows.'],prompt:'Try Two Sum again, this time making both the time and space analysis clear.',button:'Practice time & space analysis'}
};
let focus='technical',state='ready',interval=null,startedAt=0;
const starts=[...document.querySelectorAll('[data-start]')],status=document.querySelector('#status'),timer=document.querySelector('#timer');
function stage(name){document.querySelectorAll('[data-stage]').forEach(link=>{const active=link.dataset.stage===name;link.classList.toggle('is-active',active);if(active)link.setAttribute('aria-current','step');else link.removeAttribute('aria-current');});}
function tick(){const seconds=Math.floor((Date.now()-startedAt)/1000);timer.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}
document.querySelectorAll('[data-focus]').forEach(button=>button.addEventListener('click',()=>{focus=button.dataset.focus;const item=focuses[focus];document.querySelectorAll('[data-focus]').forEach(b=>{const active=b===button;b.setAttribute('aria-pressed',String(active));b.closest('.feedback-detail').classList.toggle('selected',active);b.textContent=focuses[b.dataset.focus].button+(active?' ✓':' →');});document.querySelector('#focus-title').textContent=item.title;document.querySelector('#focus-reason').textContent=item.reason;document.querySelector('#return-prompt').textContent=item.prompt;const plan=document.querySelector('#practice-plan');plan.replaceChildren();item.steps.forEach(text=>{const li=document.createElement('li');li.textContent=text;plan.append(li);});if(state!=='active')stage('return');}));
function begin(returning){if(state==='active')return;state='active';starts.forEach(button=>button.disabled=true);document.querySelector('#practice-tools').hidden=false;document.querySelector('#end').hidden=false;document.querySelector('#reset').hidden=false;document.querySelector('#notes').value='';document.querySelector('#question-label').textContent=returning?'YOUR NEXT ATTEMPT':'YOUR FIRST QUESTION';document.querySelector('#session-focus').textContent=returning?focuses[focus].prompt:'First, clarify your assumptions. Then talk through the solution and its tradeoffs.';document.querySelector('#greeting').textContent=returning?'Welcome back. Let’s work on one useful improvement: '+focuses[focus].title:'Let’s begin. Explain how you would approach the question, and talk me through your reasoning.';document.querySelector('#action-note').textContent='Your sample session is active. Finish it in the room to reflect.';status.textContent='● Sample interview in progress';stage('rehearse');startedAt=Date.now();tick();interval=setInterval(tick,1000);document.querySelector('#notes').focus();}
starts.forEach(button=>button.addEventListener('click',()=>begin(button.dataset.session==='return')));
document.querySelector('#end').addEventListener('click',()=>{if(state!=='active')return;state='review';clearInterval(interval);interval=null;starts.forEach(button=>button.disabled=false);document.querySelector('#end').hidden=true;status.textContent='✓ Sample session complete';document.querySelector('#greeting').textContent='Take a moment to reflect. The example feedback below shows how a useful review can become your next practice focus.';document.querySelector('#action-note').textContent='Sample complete. Review the illustrative feedback, then choose a focus for your next attempt.';stage('reflect');document.querySelector('#reflect-title').focus();});
document.querySelector('#reset').addEventListener('click',()=>{clearInterval(interval);interval=null;state='ready';starts.forEach(button=>button.disabled=false);document.querySelector('#practice-tools').hidden=true;document.querySelector('#reset').hidden=true;document.querySelector('#notes').value='';timer.textContent='00:00';status.textContent='● Ready when you are';document.querySelector('#question-label').textContent='QUESTION PREVIEW';document.querySelector('#session-focus').textContent='First, clarify your assumptions. Then talk through the solution and its tradeoffs.';document.querySelector('#greeting').textContent='Let’s practice your reasoning, then look at what could make your next answer stronger.';document.querySelector('#action-note').textContent='Start with a realistic question. Leave with a useful next step.';stage('rehearse');starts[0].focus();});
